// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to the caller. Use to verify connectivity.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/get-org-info.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_org_info_default = defineTool2({
  name: "get_org_info",
  title: "Get organization info",
  description: "Return public information about World Changers Mental Health Care Organisation: mission, contact email, website, and social links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "World Changers Mental Health Care Organisation",
      mission: "Providing accessible mental health care, community outreach, and advocacy across South Africa.",
      website: "https://world-changers-org.lovable.app",
      contact_email: "info@worldchangersmh.org",
      focus_areas: [
        "Mental health care and counselling",
        "Community outreach and philanthropy",
        "Youth development and advocacy"
      ]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-programs.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var PROGRAMS = [
  {
    name: "Individual Counselling",
    description: "One-on-one sessions with qualified mental health professionals, by appointment only."
  },
  {
    name: "Community Outreach",
    description: "Regular outreach programmes serving vulnerable communities with food, clothing, and mental health support."
  },
  {
    name: "Youth Development",
    description: "Workshops and mentorship focused on emotional wellbeing and life skills for young people."
  },
  {
    name: "Advocacy & Awareness",
    description: "Public campaigns that reduce stigma and promote mental health awareness in South Africa."
  }
];
var list_programs_default = defineTool3({
  name: "list_programs",
  title: "List programs",
  description: "List the public programmes offered by World Changers Mental Health Care Organisation.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(PROGRAMS, null, 2) }],
    structuredContent: { programs: PROGRAMS }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "world-changers-mcp",
  title: "World Changers MHCO",
  version: "0.1.0",
  instructions: "Public tools exposing World Changers Mental Health Care Organisation information: organisation profile, programmes, and a connectivity echo tool. Use `get_org_info` for mission and contact info, `list_programs` for programme details, and `echo` to verify the connection.",
  tools: [echo_default, get_org_info_default, list_programs_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
